# Generated by Django 5.0.6 on 2024-10-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userunisource_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userunisource',
            name='is_lazy_user',
        ),
        migrations.AddField(
            model_name='userunisource',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
