databases:
  - name: unisource
    plan: free
    databaseName: unisource
    user: unisource

services:
  - type: web
    plan: free
    name: unisource
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn unisource.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: unisource
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4