# Generated by Django 4.2.6 on 2024-05-14 21:54

from django.db import migrations, models
import django.db.models.deletion
import resource.models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='resource.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=400, upload_to='files/', validators=[resource.models.validate_file_type]),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
