# Generated by Django 5.0.6 on 2024-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_rename_date_added_favoriteresource_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
