# Generated by Django 5.0.6 on 2024-10-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': [('view_book', 'Can view book'), ('add_book', 'Can add book'), ('change_book', 'Can change book'), ('delete_book', 'Can delete book')]},
        ),
    ]
